global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'virtualdom-monitor'
    environment: 'production'

scrape_configs:
  # Virtual DOM Gateway metrics
  - job_name: 'virtualdom-gateway'
    static_configs:
      - targets: ['gateway:9090']
        labels:
          service: 'gateway'
          component: 'core'

  # GitHub Bridge metrics
  - job_name: 'github-bridge'
    static_configs:
      - targets: ['github-bridge:9091']
        labels:
          service: 'github-bridge'
          component: 'sync'

  # MongoDB exporter (if added)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          service: 'mongodb'
          component: 'database'

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          component: 'system'

# Alerting rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']